# Generated by Django 6.0.3 on 2026-04-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='nim',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
