# Generated by Django 6.0.3 on 2026-04-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_adminuser_must_change_password_adminuser_nim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin')], default='admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('suspended', 'Suspendu'), ('inactive', 'Inactif')], default='active', max_length=50),
        ),
    ]
