# Generated by Django 6.0.3 on 2026-04-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_alter_adminuser_role_alter_adminuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
