from decimal import Decimal

DEFAULT_MONTHLY_CONTRIBUTION = Decimal("1200.00")
DEFAULT_PAYMENT_MONTHS = 1

MEMBER_STATUS_ACTIVE = "active"
MEMBER_STATUS_SUSPENDED = "suspended"
MEMBER_STATUS_INACTIVE = "inactive"

ADMIN_STATUS_ACTIVE = "active"
ADMIN_STATUS_SUSPENDED = "suspended"
ADMIN_STATUS_INACTIVE = "inactive"

ADMIN_ROLE_SUPER = "super_admin"
ADMIN_ROLE_STANDARD = "admin"

MAX_MEMBER_PIN_ATTEMPTS = 3
TEMP_ADMIN_PASSWORD_LENGTH = 12
TEMP_MEMBER_PIN_LENGTH = 5