# Generated by Django 6.0.3 on 2026-04-06 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('target_type', models.CharField(blank=True, max_length=50, null=True)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='success', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.adminuser')),
            ],
        ),
    ]
