# Generated by Django 6.0.3 on 2026-04-11 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admins', '0002_adminuser_must_change_password_adminuser_nim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(blank=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/photos/')),
                ('id_card_type', models.CharField(choices=[('CIP', 'CIP'), ('NPI', 'NPI'), ('CEDEAO', 'CEDEAO'), ('PASSEPORT', 'PASSEPORT')], max_length=20)),
                ('id_card_number', models.CharField(max_length=100, unique=True)),
                ('id_card_front', models.ImageField(blank=True, null=True, upload_to='members/id_cards/front/')),
                ('id_card_back', models.ImageField(blank=True, null=True, upload_to='members/id_cards/back/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='members/signatures/')),
                ('member_pin', models.CharField(blank=True, max_length=5, null=True)),
                ('emergency_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('must_change_pin', models.BooleanField(default=False)),
                ('failed_pin_attempts', models.PositiveIntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.adminuser')),
            ],
        ),
    ]
