# Generated by Django 6.0.3 on 2026-04-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_infopost_officialcontract_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_pin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
