# Generated by Django 6.0.3 on 2026-04-15 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_member_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='FedapayPaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=150, null=True)),
                ('nim', models.CharField(max_length=50)),
                ('months', models.PositiveIntegerField(default=1)),
                ('monthly_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_url', models.TextField(blank=True, null=True)),
                ('fedapay_payload', models.JSONField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fedapay_attempts', to='members.member')),
            ],
        ),
    ]
