# Generated by Django 6.0.3 on 2026-04-18 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_alter_adminuser_role_alter_adminuser_status'),
        ('members', '0005_fedapaypaymentattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_active',
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to='admins.adminuser'),
        ),
        migrations.AlterField(
            model_name='member',
            name='id_card_number',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='nim',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('suspended', 'Suspendu')], default='active', max_length=50),
        ),
        migrations.AddIndex(
            model_name='fedapaypaymentattempt',
            index=models.Index(fields=['member', 'status'], name='members_fed_member__268fc4_idx'),
        ),
        migrations.AddIndex(
            model_name='fedapaypaymentattempt',
            index=models.Index(fields=['created_at'], name='members_fed_created_0b4b79_idx'),
        ),
        migrations.AddIndex(
            model_name='membertransaction',
            index=models.Index(fields=['member', 'transaction_type', 'status'], name='members_mem_member__f9d1c7_idx'),
        ),
        migrations.AddIndex(
            model_name='membertransaction',
            index=models.Index(fields=['created_at'], name='members_mem_created_24cc6b_idx'),
        ),
    ]
