# Generated by Django 6.0.3 on 2026-04-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_remove_member_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfoPost',
        ),
        migrations.RemoveField(
            model_name='membercontractsubmission',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='membercontractsubmission',
            name='member',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='member',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='processed_by',
        ),
        migrations.AlterField(
            model_name='membertransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('success', 'Succès'), ('failed', 'Échoué')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='membertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('payment', 'Paiement')], max_length=20),
        ),
        migrations.DeleteModel(
            name='OfficialContract',
        ),
        migrations.DeleteModel(
            name='MemberContractSubmission',
        ),
        migrations.DeleteModel(
            name='WithdrawalRequest',
        ),
    ]
