# Generated by Django 6.0.3 on 2026-04-21 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_adminuser_failed_login_attempts_adminuser_is_locked'),
        ('members', '0007_delete_infopost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='members/info_posts/images/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='info_posts', to='admins.adminuser')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
