# Generated by Django 6.0.3 on 2026-04-22 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_adminuser_failed_login_attempts_adminuser_is_locked'),
        ('members', '0008_infopost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('payment', 'Paiement'), ('withdrawal', 'Retrait')], max_length=20),
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receiver_phone', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='members.member')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to='admins.adminuser')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_request', to='members.membertransaction')),
            ],
            options={
                'indexes': [models.Index(fields=['member', 'status'], name='members_wit_member__6e0422_idx'), models.Index(fields=['created_at'], name='members_wit_created_9b9e73_idx')],
            },
        ),
    ]
