# Generated by Django 6.0.3 on 2026-04-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_membertransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membertransaction',
            name='receipt_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True),
        ),
    ]
